### ISSUE TITLE
Old version on atmosphere

### ISSUE THREAD

**Issue by tobias-f** [jedwards1211/react-meteor-data#3]
Hello.

I saw that the newest version of your package is 0.2.11. However, if I run meteor add react-meteor-data I get version 0.2.9.

Any idea why?

Thanks a lot...

**Comment by jedwards1211** [comment]
Uhoh, it seems I'm causing confusion.  This is not the official Meteor `react-meteor-data` package, it's a fork that works as an npm package.  I'll update the README to note this.
