### ISSUE TITLE
Need fix from official package to prevent warning

### ISSUE THREAD

**Issue by j18ter** [jedwards1211/react-meteor-data#5]
The following warning:
`"Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class" modules.js:1534:7`
is logged with current versions of React. The official react-meteor-data package has a fix for this. Can this fix be pulled-in from the offical package?

**Comment by bciach** [comment]
Hey lads, is anyone going to fix this problem anytime soon?

**Comment by jedwards1211** [comment]
@Rachomir @j18ter was this not fixed by #1?

**Comment by jedwards1211** [comment]
Oh, I think I just forgot to release a new version after that PR

**Comment by jedwards1211** [comment]
Okay, published as `react-meteor-data@0.2.11`.  Sorry about that!

**Comment by bciach** [comment]
Cheers!
